theme: minima
title: Equipe AnalisaR
author: Vitor Borges-Júnior
email: vntborgesjr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  AnalisaR é uma consultoria especializada em ciência de dados. 
  Nossa missão é transformar dados em informação para orientar sua tomada de decisão. 
  Atuamos em todas as áreas de negócio e pesquisa.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  vntborgesjr # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
